const motivationalQuotes: string[] = [
    'Success is not final, failure is not fatal: It is the courage to continue that counts.',
    'The only way to do great work is to love what you do.',
    'Believe you can and you\'re halfway there.',
    'Don\'t watch the clock; do what it does. Keep going.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'Your time is limited, don\'t waste it living someone else\'s life.',
    'It always seems impossible until it\'s done.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The way to get started is to quit talking and begin doing.',
    'The only person you are destined to become is the person you decide to be.',
    'Success usually comes to those who are too busy to be looking for it.',
    'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'Don\'t be afraid to give up the good to go for the great.',
    'You are never too old to set another goal or to dream a new dream.',
    'Opportunities don\'t happen. You create them.',
    'If you are working on something that you really care about, you don\'t have to be pushed. The vision pulls you.',
    'Success is not in what you have, but who you are.',
    'The only way to achieve the impossible is to believe it is possible.',
    'Your attitude, not your aptitude, will determine your altitude.',
    'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.',
    'It\'s not whether you get knocked down, it\'s whether you get up.',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    'Do not wait to strike till the iron is hot, but make it hot by striking.',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The only way to achieve the impossible is to believe it is possible.',
    'Success usually comes to those who are too busy to be looking for it.',
    'Don\'t be afraid to give up the good to go for the great.',
    'Success is not in what you have, but who you are.',
    'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.',
    'It\'s not whether you get knocked down, it\'s whether you get up.',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    'Do not wait to strike till the iron is hot, but make it hot by striking.',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The only way to achieve the impossible is to believe it is possible.',
    'Success usually comes to those who are too busy to be looking for it.',
    'Don\'t be afraid to give up the good to go for the great.',
    'Success is not in what you have, but who you are.',
    'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.',
    'It\'s not whether you get knocked down, it\'s whether you get up.',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    'Do not wait to strike till the iron is hot, but make it hot by striking.',
    'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
    'The only limit to our realization of tomorrow will be our doubts of today.',
    'The only way to achieve the impossible is to believe it is possible.',
    'Success usually comes to those who are too busy to be looking for it.',
    'Don\'t be afraid to give up the good to go for the great.',
    'Success is not in what you have, but who you are.',
];
  
export default motivationalQuotes;
  